### ISSUE TITLE
Allowing testdox after filtering

### ISSUE THREAD

**Issue by phily245** [spatie/phpunit-watcher#108]
When I pass in the `--testdox` flag into the initial command from the CLI, I get my results shown in the nice testdox format. When I use a filter, I then lose that flag and it reverts back to the standard PHPUnit output.

I can see two options for a feature here:

- Preserving all none filter flags from the initial command line argument
- Adding a testdox screen

Happy to have a crack at this myself, but was wondering what the maintainers/community thought the best path to tackle this from was?

I can see the argument preservation has been mentioned once before in #35 so I guess that's 1 vote for that?

**Comment by freekmurze** [comment]
> Preserving all none filter flags from the initial command line argument

Seems the simplest solution. Go for it!
