### ISSUE TITLE
Wait for path to be recreated

### ISSUE THREAD

**Issue by kharysharpe** [spatie/phpunit-watcher#111]
Hey, 

I have an issue where I am testing code generated and frequently blow away the folder to generate fresh code, this gives the following error:

```
In RecursiveDirectoryIterator.php line 48:
                                                                                                                                   
RecursiveDirectoryIterator::__construct(/foo/bar/output): failed to open dir: No such file or directory
```

It would be good to have an option to wait for path to exist similar to ```tail -F | tail --retry```

Would this be a good addition?

**Comment by freekmurze** [comment]
Feel free to PR this. 👍
