### ISSUE TITLE
Cannot redeclare composerRequireb11547267c7e277f051472ea89485cca

### ISSUE THREAD

**Issue by notflip** [spatie/phpunit-watcher#114]
```
PHP Fatal error:  Cannot redeclare composerRequireb11547267c7e277f051472ea89485cca() (previously declared in /Users/miguel/code/vjr001/vendor/composer/autoload_real.php:66) in /Users/miguel/Code/vjr001/vendor/composer/autoload_real.php on line 66
```

I tried installing both globally and local, running with `vendor/bin/phpunit-watcher watch`, but both optios gave me this error

![Screenshot 2020-06-16 at 10 57 29](https://user-images.githubusercontent.com/4146384/84754115-32422a00-afc0-11ea-81db-637cbf61d063.png)

**Comment by juliancesar** [comment]
I'm having the same issue from a fresh install of Laravel 9. I'm using php 8.0. Please help!
