### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by ricardogobbosouza** [spatie/phpunit-watcher#127]
Release forecast for php 8 support?

**Comment by freekmurze** [comment]
Feel free to send a PR, make sure all tests pass.

**Comment by ricardogobbosouza** [comment]
@freekmurze 
Actually it already has support https://github.com/spatie/phpunit-watcher/blob/master/composer.json#L19
So we don't have a version = /

**Comment by freekmurze** [comment]
Ah, just tagged a new version 👍
