### ISSUE TITLE
PHPUnit arguments from config are wiped out when changing group 

### ISSUE THREAD

**Issue by iandunn** [spatie/phpunit-watcher#129]
### Reproduction Steps

1. Add PHPUnit arguments to `phpunit-watcher.yml.dist`:
    ```yml
     phpunit:
      arguments: -d xdebug.mode=off --process-isolation
     ```
    
1. Start `phpunit-watcher`, and see the expected output:
     > Starting PHPUnit with arguments: `-d xdebug.mode=off --process-isolation`

1. Use the menu to change the `group` (or `filter`, `file`, etc)
1. See that `phpunit-watcher.yml.dist` arguments are no longer used:
    > Starting PHPUnit with arguments: `--group=patterns`

In one of my codebases, that makes `phpunit-watcher` unusable, because the config arguments are required on every run (see #128).

### Potential Solution

On each run, the user-supplied arguments (`--group=patterns`) could be merged with the default arguments from `phpunit-watcher.yml`. User-supplied would override config arguments, but other config arguments would be preserved.

### Full output:

```
> composer run test:watch
> phpunit-watcher watch


PHPUnit Watcher
===============

 PHPUnit Watcher 1.12.1 by Spatie and contributors.

 Using options from configfile at `/public_html/phpunit-watcher.yml.dist`

 Tests will be rerun when *.php files are modified in
 * /public_html/./events/
 * /public_html/./patterns/


PHPUnit 9.5.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.14
Configuration: /public_html/phpunit.xml.dist

................................................................. 65 / 81 ( 80%)
...........I....                                                  81 / 81 (100%)

Time: 00:09.924, Memory: 10.00 MB

There was 1 incomplete test:

1) Dotorg\API\Events\Tests\Test_Events::test_port_remaining_tests
Not all of the tests from ./test-index.php have been ported to PHPUnit yet. See the notes in that file.

/public_html/events/1.0/tests/test-index-phpunit.php:1149

OK, but incomplete, skipped, or risky tests!
Tests: 81, Assertions: 111, Incomplete: 1.
Starting PHPUnit with arguments: `-d xdebug.mode=off --process-isolation`


Press a to run all tests.
Press t to filter by test name.
Press p to filter by file name.
Press g to filter by group name.
Press s to filter by test suite name.
Press r to run tests with a random seed.
Press q to quit the watcher.
Press Enter to trigger a test run.
g


Pattern mode usage
Type a pattern and press Enter to only run tests from a specific PHPUnit group.
Press Enter with an empty pattern to execute all tests in all files.

Start typing to filter by a test name.
pattern > patterns

PHPUnit 9.5.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.14
Configuration: /public_html/phpunit.xml.dist

....                                                                4 / 4 (100%)

Time: 00:00.387, Memory: 8.00 MB

OK (4 tests, 14 assertions)

Starting PHPUnit with arguments: `--group=patterns`
```

**Comment by iandunn** [comment]
@freekmurze , would you accept a PR that fixes this?

**Comment by freekmurze** [comment]
Yup, please send a PR 👍

**Comment by iandunn** [comment]
Hi @freekmurze , regular contributors don't have access to re-open issues, but this is still an active bug. Do you mind re-opening this?

There's a promising fix in #130, but it's blocked waiting for some feedback.

**Comment by iandunn** [comment]
@freekmurze , since #130 was too much complexity, do you have any thoughts on other approaches to solve this?

**Comment by iandunn** [comment]
Bumping to keep open.

**Comment by iandunn** [comment]
>  If you feel this issue deserves some attention from my human colleagues feel free to reopen it.

Hi @freekmurze , regular contributors don't have access to re-open issues, but this is still an active bug. Do you mind re-opening this?

I think the next step is to get your feedback on https://github.com/spatie/phpunit-watcher/issues/129#issuecomment-867894955
