### ISSUE TITLE
[BUG] Array to string conversion in WatcherCommand on line 121

### ISSUE THREAD

**Issue by dkd-kaehm** [spatie/phpunit-watcher#143]
The `fileMask` can be an array, which works as expected, but by starting the watching the warn notice is shown and the message does not contain the configured fileMask properly.

See:

https://github.com/spatie/phpunit-watcher/blob/cf2f5e6994934f364f38c503c00eebaad905fbb8/src/WatcherCommand.php#L121

**Comment by freekmurze** [comment]
Feel free to send a PR with a fix.
