### ISSUE TITLE
Какой-то страшный хэштег

### ISSUE THREAD

**Issue by IlyaVorozhbit** [spatie/phpunit-watcher#148]
Привет! :ru: 

Хотел сказать, что у вас странный хэштег появился в пхпюнитвотчере

#StandWithUkraine

Удолите плиз, бесит

или добавьте ещё

#GoodLuckTheUsa

**Comment by IlyaVorozhbit** [comment]
ок, господам дизлайкерам объясню: я не имею политической точки зрения никакой. политика для политиков

**Comment by IlyaVorozhbit** [comment]
обычных граждан оскорблять не собираюсь и не делаю этого ни в коем случае, это посыл (кому?) - политикам

**Comment by s-chizhik** [comment]
Searching politicians on GitHub? Lol

**Comment by IlyaVorozhbit** [comment]
ставьте любые реакции, какие захотите, мне - всё равно. что хотел донести - донёс. остальное - дело ваше.

**Comment by s-chizhik** [comment]
@IlyaVorozhbit so proudly talked about the position and closed the issue.

Lol

**Comment by IlyaVorozhbit** [comment]
@s-chizhik #StopHatingRussia

**Comment by IlyaVorozhbit** [comment]
![image](https://user-images.githubusercontent.com/5056861/167906818-955b94bb-9ae2-4c9b-9657-b22c5f1688a0.png)
think about it

**Comment by s-chizhik** [comment]
@IlyaVorozhbit 

> @s-chizhik ти ж знаєш російську, давай на ній поговоримо

> Using non-conventional language here you are only showing your disrespect to the community

I know a couple of languages and choose appropriate for any community I'm in. You are (russians) the only source of russophobia. Don't put your responsibility on the rest of the world.

**Comment by s-chizhik** [comment]
You can make your own helpful Laravel packages and put any hashtag you consider appropriate.

**Comment by IlyaVorozhbit** [comment]
Ок бро Просто ты мне говоришь про мирных жителей У меня брат в Киеве. Хочешь продолжить действительно этот диалог? --Отправлено из мобильной Яндекс Почты11.05.2022, 20:08, "Sergey Chizhik" ***@***.***>:
You can make your own helpful Laravel packages and put any hashtag you consider appropriate.

**Comment by s-chizhik** [comment]
@IlyaVorozhbit you have started this issue, and you are continuing to discuss it 🤷‍♂️

Just stop writing messages, and this dialog will be ended.
