### ISSUE TITLE
Looking Good...

### ISSUE THREAD

**Issue by mikeerickson** [spatie/phpunit-watcher#15]
@freekmurze  I know this is not an issue, but just wanted to share output with our live test (includes using our phpunit printer) -- https://github.com/mikeerickson/phpunit-pretty-result-printer

![image](https://user-images.githubusercontent.com/183153/28897827-5fe2486e-7797-11e7-977b-148ac14db3ea.png)

**Comment by freekmurze** [comment]
That looks very good.  But I'm not going to include that result printer by default. People can install it manually if they want it.

**Comment by mikeerickson** [comment]
@freekmurze I am not suggesting you include at all.... Just saying I liked the combination.

**Comment by freekmurze** [comment]
The combination looks very good indeed 😄
