### ISSUE TITLE
Installation failed Laravel 9 PHP 8.1

### ISSUE THREAD

**Issue by gaztum** [spatie/phpunit-watcher#152]
Using version ^1.23 for spatie/phpunit-watcher
./composer.json has been updated
Running composer update spatie/phpunit-watcher
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - spatie/phpunit-watcher[1.23.5, ..., 1.23.6] require yosymfony/resource-watcher ^2.0 | ^3.0 -> satisfiable by yosymfony/resource-watcher[v2.0.0, v2.0.1, v3.0.0, 3.0.x-dev].
    - spatie/phpunit-watcher 1.23.0 requires php ^7.2 -> your php version (8.1.13) does not satisfy that requirement.
    - spatie/phpunit-watcher 1.23.1 requires symfony/console ^5.0 -> found symfony/console[v5.0.0-BETA1, ..., 5.4.x-dev] but the package is fixed to v6.2.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - spatie/phpunit-watcher[1.23.2, ..., 1.23.4] require symfony/console ^5.2 -> found symfony/console[v5.2.0-BETA1, ..., 5.4.x-dev] but the package is fixed to v6.2.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - yosymfony/resource-watcher v2.0.0 requires symfony/finder ^2.7|^3.0|^4.0 -> found symfony/finder[v2.7.0-BETA1, ..., 2.8.x-dev, v3.0.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev] but the package is fixed to v6.2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - yosymfony/resource-watcher[v2.0.1, v3.0.0, ..., 3.0.x-dev] require symfony/finder ^2.7|^3.0|^4.0|^5.0 -> found symfony/finder[v2.7.0-BETA1, ..., 2.8.x-dev, v3.0.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev] but the package is fixed to v6.2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires spatie/phpunit-watcher ^1.23 -> satisfiable by spatie/phpunit-watcher[1.23.0, ..., 1.23.6].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require spatie/phpunit-watcher:*" to figure out if any version is installable, or "composer require spatie/phpunit-watcher:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by markib** [comment]
same issue here also

**Comment by jjcc1421** [comment]
We need to wait this pull request, that's causing most of the issues
https://github.com/yosymfony/resource-watcher/pull/12

**Comment by robsontenorio** [comment]
Is there any other compatible alternative?

**Comment by daniel-aime** [comment]
I also encountered this problem, and for the moment, i have never found the solution but I used another alternatives package`composer require pkboom/laravel-test-watcher`

**Comment by Kanti** [comment]
@spatie-bot this is not fixed
