### ISSUE TITLE
Update package dep for symfony console

### ISSUE THREAD

**Issue by michaelw85** [spatie/phpunit-watcher#159]
I cannot install phpunit-watcher due to a version constraint on the symfony/console package. 
`- spatie/phpunit-watcher[1.23.5, ..., 1.23.6] require symfony/console ^5 | ^6`.

In my project I have v7 installed of the symfony console package.
Can this version be added as an acceptable dependency?

**Comment by freekmurze** [comment]
Feel free to send a PR for this 👍

**Comment by michaelw85** [comment]
PR has been created.
