### ISSUE TITLE
Consider support --include-group and --exclude-group in configuration file

### ISSUE THREAD

**Issue by mikeerickson** [spatie/phpunit-watcher#17]
In addition to the `testSuites` would also be nice to have `--include-group` and `--exclude-group` options as part of the default execution (as configured in `.phpunit-watcher.yml`).

Currently, I have this configured for each project (in the package composer.json) but I often have grouping and suites running.

watch:
  directories:
    - src
    - tests
  fileMask: '*.php'
  testSuites:
    - unit
    - feature
  excludeGroups:
    - group1
    - group2
  includeGroups:
    - group3
    - group4

**Comment by freekmurze** [comment]
Thanks for your suggestion. Currently I'm not too open for it, same reasoning as my answer in #16
