### ISSUE TITLE
Show desktop notifications

### ISSUE THREAD

**Issue by freekmurze** [spatie/phpunit-watcher#20]
It would be nice if the tool were to send a notification when the tests succeed/fail.

Integrating [JoliNotif](https://github.com/jolicode/JoliNotif) seems like the way to go.

There also should be a config option in the `phpunit-watcher.yml` to turn off notifications.

**Comment by vyuldashev** [comment]
@freekmurze Looks like the feature is completed. Waiting for your feedback.

**Comment by freekmurze** [comment]
We'll handle this further in #23

**Comment by freekmurze** [comment]
Done 🎉
