### ISSUE TITLE
Issue with install latest version

### ISSUE THREAD

**Issue by mikeerickson** [spatie/phpunit-watcher#22]
As you can see by the screenshot below, something is amiss as it relates to using the `--version` flag.

![image](https://user-images.githubusercontent.com/183153/28985003-6475f144-7915-11e7-94b7-dd53aeb44e66.png)

During install, it appears that latest version (1.1.0 at the time of submission) however, checking version `phpunit-watcher --version` it still reports v1.0.4

**Comment by mikeerickson** [comment]
Appears version is hardcoded, thinking version string should be set in the package composer.json

```
class ConsoleApplication extends Application
{
    public function __construct()
    {
        parent::__construct('PHPUnit Watcher', '1.0.4');

        $this->add(new WatcherCommand());
    }

    public function getLongVersion()
    {
        return parent::getLongVersion().' by <comment>Spatie</comment>';
    }
}
```

**Comment by freekmurze** [comment]
Do you know how to make this number dynamic?
