### ISSUE TITLE
Version info does not match tagged version

### ISSUE THREAD

**Issue by mikeerickson** [spatie/phpunit-watcher#45]
Hey there, just a soft nudge that the version is out of sync again :-)

FWIW, I store the `version` in `composer.json` and then directly read from there.  I know it is a pain to keep them in sync with what `packagist.org` shows, guess that is part of software development. 
Thanks for this package though, I have gotten great use from it!

Let me know if you want a contribution on this item.

```
class ConsoleApplication extends Application
{
    public function __construct()
    {
        parent::__construct('PHPUnit Watcher', '1.3.1'); 

        $this->add(new WatcherCommand());
    }

    public function getLongVersion()
    {
        return parent::getLongVersion().' by <comment>Spatie</comment>';
    }
}
```

**Comment by freekmurze** [comment]
I've removed the version number in the current master. It's too bothersome to update.

`composer global show` will always shows the correct version number anyways.
