### ISSUE TITLE
TTY mode is not supported on Windows platform

### ISSUE THREAD

**Issue by dwikip** [spatie/phpunit-watcher#48]
Hi,
Im trying to use phpunit-watcher in windows machine, but got error 

> TTY mode is not supported on Windows platform.

can i do something to make it work in windows?

Thanks

**Comment by freekmurze** [comment]
I'm not a Windows user, so I don't know.

**Comment by spaceemotion** [comment]
@dwikip you can try to use the VSCode terminal instead (MingW seems to work fine as well).
