### ISSUE TITLE
Keystroke options dont work when watcher executed from composer script

### ISSUE THREAD

**Issue by mfour-merickson** [spatie/phpunit-watcher#54]
As developer, if I launch the Watcher command from a composer.json script, the keyboard watcher does not work

```
...
  "scripts": {
    "test": "vendor/bin/phpunit --colors=always",
    "watch-tickets": "vendor/bin/phpunit-watcher watch --testsuite Tickets"
  }
...
```

```
Press a to run all tests.
Press t to filter by test name.
Press p to filter by file name.
Press q to quit the watcher.
Press Enter to trigger a test run.
```

The actual keystroke is sent to the console, but the actions are not triggered

![image](https://user-images.githubusercontent.com/31225533/34308762-a5a89e1c-e703-11e7-86a4-24f178707eb2.png)

**Comment by mfour-merickson** [comment]
I have figured this one out (here is the trick in the event someone else has the problem)

```
...
  "scripts": {
    "test": "vendor/bin/phpunit --colors=always",
    "watch-tickets": "vendor/bin/phpunit-watcher watch --testsuite Tickets  < /dev/tty"
  }
...
```

**Comment by fotonmoton** [comment]
I think @mfour-merickson`s trick should be in docs
