### ISSUE TITLE
yosymfony/Resource-watcher outdated

### ISSUE THREAD

**Issue by faustbrian** [spatie/phpunit-watcher#55]
This package relies on https://github.com/yosymfony/Resource-watcher which prevents using it in Laravel 5.6 because it doesn't allow Symfony 4.0.

Package looks unmaintained so might be time to fork it or integrate it directly into the package?

**Comment by erikgaal** [comment]
Made a PR to add Symfony 4 support. yosymfony/resource-watcher#5

**Comment by faustbrian** [comment]
Would probably be better to integrate this packages functionality into the core to prevent this from happening in the future, especially with how unmaintained that package is.

**Comment by erikgaal** [comment]
I agree with you completely, @faustbrian, I'll look into it.
