### ISSUE TITLE
Fail to detect the phpunit path if composer `bin-dir` config is used

### ISSUE THREAD

**Issue by Spy-Seth** [spatie/phpunit-watcher#61]
It seems that `phpunit-watcher` is failling to detect the phpunit path when composer is configured to move the binaries outside the `vendor` directory:
```json
"config": {
  "bin-dir": "bin"
}
```

The `phpunit-watcher` will output:

```
sh: vendor/bin/phpunit: No such file or directory
```

It could be a good idea to use the `config.bin-dir` value to determine the composer binary direcotry path

**Comment by romainnorberg** [comment]
Duplicate of #66 ?

**Comment by freekmurze** [comment]
Duplicate of #66 indeed
