### ISSUE TITLE
Symfony process ProcessTimedOutException

### ISSUE THREAD

**Issue by beyondcompute** [spatie/phpunit-watcher#63]
Hello! 

I am getting this while running `phpunit-watcher`:
```
  [Symfony\Component\Process\Exception\ProcessTimedOutException]               
  The process "phpunit-watcher watch --colors=always --testdox --bootstrap ve  
  ndor/autoload.php *Test.php" exceeded the timeout of 300 seconds. 
```

Symfony 4.0.0

**Comment by mykeels** [comment]
@beyondcompute I got around this by wrapping phpunit-watcher with [nodemon](https://github.com/remy/nodemon).

```bash
nodemon --watch ./app --watch ./tests/ -e php --exec composer watch
```

Where `composer watch` is defined in my `composer.json` scripts as

```
"watch": [
     "phpunit-watcher watch"
]
```

**Comment by mykeels** [comment]
Hey, @beyondcompute ... I found that setting the `--timeout` flag to 0 makes it run forever, so you may not have to wrap it with `nodemon` after all.

```bash
./vendor/bin/phpunit-watcher watch --timeout 0
```

**Comment by beyondcompute** [comment]
Thanks again @mykeels! Thatʼs really good advice!

**Comment by joaoeduardo** [comment]
This flag doesn't work for me

**Comment by freekmurze** [comment]
Closing this, as this is solved for most people.

**Comment by iandunn** [comment]
This worked for me in `composer.json`, for version `1.11.1`:

```json
"config" : {
	"process-timeout": 0
},
```

I tried setting the env var for just the `test:watch` task...

```json
"scripts" : {
	"test"       : "phpunit",
	"test:watch" : "COMPOSER_PROCESS_TIMEOUT=0 vendor/bin/phpunit-watcher watch"
}
```
...but couldn't get that working 🤷‍♂

**Comment by crux** [comment]
nothing of the above works :(

1. COMPOSER_PROCESS_TIMEOUT=0 
has no effect. 

2. ./vendor/bin/phpunit-watcher watch --timeout 0
does not even exists:

....
PHPUnit 9.5.20 #StandWithUkraine
Unknown option "--timeout"

**Comment by iandunn** [comment]
Did you try [`config.process-timeout` in `composer.json`](https://github.com/spatie/phpunit-watcher/issues/63#issuecomment-545633709)? That's still working for me.

**Comment by crux** [comment]
I do not even use composer for running the script. What was finally working was adding a config file setting:

```sh
$ cat >> .phpunit-watcher.yml
phpunit:
  timeout: 180
^D
```

interestingly, I could not find a way to set this option via any other means, like phpunit.xml for example. 

I realy hate this ecosystem. So many packages, so unbelievable bad quality, so much crappy software,

**Comment by iandunn** [comment]
The advice from the `README` file also worked for me:

```json
"test:watch": [
      "Composer\\Config::disableProcessTimeout",
      "phpunit-watcher watch"
],
```

**Comment by marcusorjames** [comment]
> I do not even use composer for running the script. What was finally working was adding a config file setting:
> 
> $ cat >> .phpunit-watcher.yml
> phpunit:
>   timeout: 180
> ^D
> interestingly, I could not find a way to set this option via any other means, like phpunit.xml for example.
> 
> I realy hate this ecosystem. So many packages, so unbelievable bad quality, so much crappy software,

Why this has received down votes I have no idea, it is the only thing that worked for me.
