### ISSUE TITLE
Only run tests for changed files ?

### ISSUE THREAD

**Issue by stijink** [spatie/phpunit-watcher#64]
Hi,

i just found this package. First of all thank you for that. Looks promising.

I already found that there is a pull request for not running the tests on initial startup, which is great.

But what i found out is, that `phpunit-watcher` re-runs all of my tests whenever any test changes. Having lots of tests this is rather time-consuming.

I'm aware that i could set a filter. But during development various tests may change. Is there any way to only re-run the tests for the files that actually changed ?

**Comment by freekmurze** [comment]
That isn't supported. If this behaviour can be easily added to the package, I'd accept a PR for this.

**Comment by stijink** [comment]
@freekmurze Thank you for the reply. Maybe i'll look into it.

**Comment by amacrobert** [comment]
I was just about to open a feature request for this. It's the default behavior of [this PHPUnit watch](https://github.com/slavahatnuke/hot-phpunit-runner). I do find spatie/phpunit-watcher to be more responsive and fully featured though, so it would be great if automatically running only the corresponding tests were a feature here too.

I'll try to make some time to implement it myself and open a PR.
