### ISSUE TITLE
Ability to change binary and config locations/files

### ISSUE THREAD

**Issue by lonnylot** [spatie/phpunit-watcher#66]
Right now the config file is hardcoded to `.phpunit-watcher.yml` and the binary is hardcoded to `vendor/bin/phpunit`

There are other programs that use `phpunit` and wrap custom functionality (or shortcuts) around it. An example is [Laravel Dusk](https://laravel.com/docs/5.6/dusk)

It would be helpful if we could configure both the config file to use and the binary. Configuring the binary is also helpful for people who have the binary in a different location.

Let me know if this interests others. If so, I can whip up a PR.

**Comment by romainnorberg** [comment]
hello @lonnylot 

I'm interested for this config option, the projects I'm working on integrate Phpunit as a vendor _(so the binary is located `./vendor/phpunit/phpunit/phpunit`)_

We can work together for implementation if you're interested

**Comment by lonnylot** [comment]
Hey @romainnorberg  - I hacked together something for myself, but it's a mess. It's not complete, but let me clean it up a bit and I'll post an initial draft shortly.

**Comment by romainnorberg** [comment]
thanks @lonnylot

**Comment by romainnorberg** [comment]
hello @freekmurze this issue can be closed

Best wishes!

**Comment by lonnylot** [comment]
@romainnorberg Thanks for not being lazy and throwing this together :)
