### ISSUE TITLE
exceeded the timeout of 300 seconds

### ISSUE THREAD

**Issue by oligus** [spatie/phpunit-watcher#72]
```
 [Symfony\Component\Process\Exception\ProcessTimedOutException]                                                                   
  The process "vendor/bin/phpunit-watcher watch 'tests/src/Builders/CS15XmlBuilderTest.php'" exceeded the timeout of 300 seconds. 
```
This was talked about in #63, the thread was closed but there was no resolution, the proposed solution did not work on version 1.60:

```
$ vendor/bin/phpunit-watcher --timeout 0

 The "--timeout" option does not exist. 
```

**Comment by oligus** [comment]
Alltough the timeout option does not exist, this is a timeout from  composer and it can be extended by:

```
$ export COMPOSER_PROCESS_TIMEOUT=600
```

**Comment by NicklasWallgren** [comment]
https://getcomposer.org/doc/articles/scripts.md

**To disable the timeout for every script on a given project, you can use the composer.json configuration.**

```
{
    "config": {
        "process-timeout": 0
    }
}
```

**Comment by Jehadalmaliki** [comment]
So helpful , Thanks
