### ISSUE TITLE
PHPUnit arguments configured are wiped if 'a' is used

### ISSUE THREAD

**Issue by sg3s** [spatie/phpunit-watcher#73]
Due to a line in option `a` all arguments configured are wiped. I believe this is inconsistent and it should not be the case.

The following line causes the arguments to be wiped from a run, and all subsequent runs:
https://github.com/spatie/phpunit-watcher/blob/master/src/Screens/Phpunit.php#L41 

If you use 'Enter' to re-run the initial tests it does not wipe the arguments. But if you use 'a' once you will not be able to get the arguments back until you restart the watcher.

Either the option is inconsistent, or the purpose of 'a' vs 'Enter' is not clear to me/my team.

**Comment by freekmurze** [comment]
Feel free to submit a PR for this!

**Comment by sg3s** [comment]
@freekmurze Should the functionality be the same then? 

Because then I will just update the switch to group 'Enter' and 'a' options.

**Comment by freekmurze** [comment]
`a` should clear out all options set by `g`, `s`, `t` and `p`.

**Comment by sg3s** [comment]
Aah, okay, so that explains the difference / purpose of 'a' vs 'Enter'. We're not really using those screens actively, found them to be buggy and couldn't easily find out what was wrong so we left them alone. Our main use case is just running all/changed tests on changes.

I will have to take a look to see how that is fixable then, no guarantees for a PR :)

**Comment by freekmurze** [comment]
> no guarantees for a PR :)

No problem! It's open source, I'm grateful for any PRs that improve the code, but don't feel yourself obligated in any way.
