### ISSUE TITLE
Could not start watcher

### ISSUE THREAD

**Issue by TuxBoy** [spatie/phpunit-watcher#78]
Hello,
When I try to run the `phpunit-watcher watch` it returns an error:
```
PHP Fatal error:  Uncaught Error: Call to undefined method Clue\React\Stdio\Stdio::getInput() in /home/benoit/PhpStorm/itrocks/bappli-sfkgroup/vendor/spatie/phpunit-watcher/src/Terminal.php:36
Stack trace:
```
With return 255 code.

There is a configuration to make it work?

Thank you.

**Comment by cs278** [comment]
Basically #77 has updated to new major versions of a few deps that are not supported, the whole PR should be reverted.

> PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Yosymfony\ResourceWatcher\ResourceWatcher::__construct(), 1 passed in vendor/spatie/phpunit-watcher/src/Watcher.php on line 41 and exactly 3 expected in vendor/yosymfony/resource-watcher/src/ResourceWatcher.php:41

You work around this by requiring `spatie/phpunit-watcher` version `1.8.0` or conflicting against `1.8.1`.

```sh
composer require --dev spatie/phpunit-watcher:1.8.0
```

**Comment by freekmurze** [comment]
I've tagged a new version 1.8.2 that doesn't contain the changes of #77
