### ISSUE TITLE
Remove help messages

### ISSUE THREAD

**Issue by jmsosso** [spatie/phpunit-watcher#83]
Hi,

Any way to hide the help messages shown at the end of the phpunit execution?

I want to have it running in a vscode terminal and that messages takes the half of the panel height :)

![image](https://user-images.githubusercontent.com/7966541/54819980-eeb61e80-4c9d-11e9-9bba-ce71d82b4029.png)

Thanks.

**Comment by freekmurze** [comment]
I'd accept a PR that adds a config value to hide these help messages.

**Comment by jmsosso** [comment]
Checked with hideManual: true and works as expected :)
