### ISSUE TITLE
phpunit-watcher failed to execute phpunit

### ISSUE THREAD

**Issue by yjv-XCV** [spatie/phpunit-watcher#88]
Greetings,

This is the error I get

```
sh: /myprojectpath/vendor/bin/phpunit : No such file or directory
sh: line 0: exec: /myprojectpath/vendor/bin/phpunit : cannot execute: No such file or directory
```

It seem it state that my phpunit is not exists.
However, when I execute with */myprojectpath/vendor/bin/phpunit* it works just fine.

I'd tried with default setting, and also use customised path for phpunit using phpunit-watcher.yml
with phpunit path set to
*vendor/bin/phpunit*
*vendor/phpunit/phpunit/phpunit*
Both are not working for phpunit-watcher, but when execute directly in cli, it worked.

Any idea what is going wrong?
Background:
installed locally with Laravel 5.8.*
vendor/bin/phpunit is working, and the execute permission is opened to all
composer version 1.8.6
phpunit/phpunit version ^7.5
spatie/phpunit-watcher version ^1.10
php 7.3.4 for CLI

Thanks in advance.

**Comment by xipasduarte** [comment]
I have the same issue. I'm using PHP 7.2, everything ele is the same as @yjv-XCV.

**Comment by yjv-XCV** [comment]
I actually found where the problems came from, but have no idea how to fix it.
in *vendor/symfony/process/Process.php*:229
```
$commandline = 'exec '.$commandline;
```
The command line is received from
*vendor/spatie/phpunit-watcher/src/Screens/Phpunit.php*:93
which is combination of *phpunitBinaryPath* and *phpunitArguments*.
However the problem lies when it execute exec, it take the space, and the arguments as part of the file name.
When I didn't apply any phpunit arguments, it will have a space after the phpunitBinaryPath in the $commandline, and it works after I remove the space from it.
From
```
$commandline; // output: "exec /myprojectPath/vendor/bin/phpunit "
```
change to
```
$commandline; // output: "exec /myprojectPath/vendor/bin/phpunit"
```

Please advise, if any setting need to be done to make the execution will escape the space, and treat the arguments properly.

**Comment by yjv-XCV** [comment]
After I modify 
*vendor/spatie/phpunit-watcher/src/Screens/Phpunit.php*:93
from
```
$result = (new Process(["{$this->phpunitBinaryPath} {$this->phpunitArguments}"]))

```
to
```
$result = (new Process(["{$this->phpunitBinaryPath}", "{$this->phpunitArguments}"]))
```

it works fine.
Not sure if it will break other logic of the application.

**Comment by xipasduarte** [comment]
That's great @yjv-XCV. This change works for me too.

I dug a little deeper in the docs for Symfony Process and according to the documentation since [v3.4](https://symfony.com/doc/current/components/process.html) that's how it should be, the command separate from the arguments. Only from [v3.3](https://symfony.com/doc/3.3/components/process.html) below do we find the signature that is in phpunit-watcher.

I would suggest you open a PR with the change, although we no longer need the string wrap on the arguments:
```php
$result = (new Process([$this->phpunitBinaryPath, $this->phpunitArguments]));
```

**Comment by freekmurze** [comment]
Fixed in latest version.
