### ISSUE TITLE
phpunit arguments do not preserved after filter

### ISSUE THREAD

**Issue by fotonmoton** [spatie/phpunit-watcher#91]
If you press `t` and input filter pattern watcher do not preserve phpunit arguments.
before filter:
![image](https://user-images.githubusercontent.com/7763084/62383268-15436a80-b558-11e9-8df6-6f1d8b96009e.png)
after:
![image](https://user-images.githubusercontent.com/7763084/62383320-28eed100-b558-11e9-8c9d-a0a2c8ecc49b.png)

**Comment by fotonmoton** [comment]
I can specify all options in phpunit.xml config file but `--colors=always` should be passed as argument to work.

**Comment by freekmurze** [comment]
Currently I don't have time to take a look at this, but feel free to submit a PR for this.
