### ISSUE TITLE
Use random seed

### ISSUE THREAD

**Issue by obstschale** [spatie/phpunit-watcher#93]
We use phpunit-watch in one of our projects. So first things first, Thank you!!!

Recently, we started to run our tests in random order (recommendation by Sebastian Bergmann). This showed us a lot of potential bugs, because some tests were depending each other.

It would be very helpful to use phpunit-watcher during decoupling those tests, but this requires to run tests in the same order given a random seed.

phpunit prints the seed before running the tests. Now I would like to enter this seed, so phpunit-watch uses it.

Can you tell me if this a) already possible and I missed it? or b) point me to the right direction and I will try to add this feature myself, if you think it fits :)

**Comment by freekmurze** [comment]
I don't have time to look into this now, but if you submit a simple PR, I'll consider merging it. 👍
